In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\python37.9\lib\site-packages (1.3.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\python37.9\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\python37.9\lib\site-packages (from pandas) (2020.5)
Requirement already satisfied: numpy>=1.17.3 in c:\python37.9\lib\site-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in c:\python37.9\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [1]:
import os 
import pandas as pd

In [2]:
cwd = os.getcwd()
DIR_NAM = os.path.dirname(os.getcwd())
BASE_DIR = os.path.join(DIR_NAM,'7. Build a Data Science Pipeline')
DATA_DIR = os.path.join(BASE_DIR,'data')
CACHE_DIR = os.path.join(BASE_DIR,'cache')
os.makedirs(CACHE_DIR,exist_ok=True)

In [5]:
my_data = os.path.join(DATA_DIR,'2019.csv')
df = pd.read_csv(my_data)
df

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Avengers: Endgame,"$2,797,501,328","$858,373,000",30.7%,"$1,939,128,328",69.3%
1,2,The Lion King,"$1,656,943,394","$543,638,043",32.8%,"$1,113,305,351",67.2%
2,3,Frozen II,"$1,450,026,933","$477,373,578",32.9%,"$972,653,355",67.1%
3,4,Spider-Man: Far from Home,"$1,131,927,996","$390,532,085",34.5%,"$741,395,911",65.5%
4,5,Captain Marvel,"$1,128,274,794","$426,829,839",37.8%,"$701,444,955",62.2%
...,...,...,...,...,...,...,...
195,196,An Officer and a Spy,"$18,878,658",-,-,"$18,878,658",100%
196,197,Crayon Shin-chan: Honeymoon Hurricane - The Lo...,"$18,738,951",-,-,"$18,738,951",100%
197,198,Greta,"$18,653,107","$10,532,219",56.5%,"$8,120,888",43.5%
198,199,Peppa Celebrates Chinese New Year,"$18,653,040","$131,225",0.7%,"$18,521,815",99.3%
199,200,Black Christmas,"$18,529,730","$10,429,730",56.3%,"$8,100,000",43.7%

In [7]:
df['Year'] = 2019

In [6]:

my_dataframe = []
csv_files = [x.replace('.csv','') for x in os.listdir(DATA_DIR) if x.endswith('.csv')]
csv_files.sort(reverse = True)
print(csv_files)
for filename in csv_files:
    year = filename
    csv_path = os.path.join(DATA_DIR,filename +'.csv')
    this_df = pd.read_csv(csv_path)
    this_df['filename'] = filename + '.csv'
    this_df['year'] = year
    my_dataframe.append(this_df)

['2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000']

In [7]:
my_entire_dataframe = pd.concat(my_dataframe)
my_entire_dataframe.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,"Hi, Mom","$822,009,764",-,-,"$822,009,764",100%,2021.csv,2021
1,2,F9: The Fast Saga,"$714,400,845","$172,933,845",24.2%,"$541,467,000",75.8%,2021.csv,2021
2,3,Detective Chinatown 3,"$686,257,563",-,-,"$686,257,563",100%,2021.csv,2021
3,4,Godzilla vs. Kong,"$467,863,133","$100,563,133",21.5%,"$367,300,000",78.5%,2021.csv,2021
4,5,Black Widow,"$377,689,901","$183,201,994",48.5%,"$194,487,907",51.5%,2021.csv,2021

In [9]:
dataset = os.path.join(CACHE_DIR,'movies-box-office-dataset.csv')
my_entire_dataframe.to_csv(dataset,index= False)